import { FC, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth, useCurrentRequestId } from '../../../Core/Storage/DataSlice';
import { SearchMapsRequestVerbose } from '../../../Autogenerated/Backend';
import { SearchMapsRequestAPI } from '../../../Core/APIs/SearchMapsRequestAPI';
import { LoadingIndicator } from '../../UI/LoadingIndicator';
import { MapListComponent } from '../../Maps/MapList/MapList';

interface SearchMapsRequestPageComponentProps {
    id: number;
}

export const SearchMapsRequestPageComponent: FC<SearchMapsRequestPageComponentProps> = ({ id }) => {
    const auth = useAuth();
    const navigate = useNavigate();
    const currentRequestId = useCurrentRequestId();
    const [request, setRequest] = useState<SearchMapsRequestVerbose | null | undefined>(undefined);

    useEffect(() => {
        if (auth === null) {
            navigate('../');
        }
        async function getMaps() {
            const request = await SearchMapsRequestAPI.GetRequest(id);
            setRequest(request);
        }
        getMaps();
    }, [auth, navigate, id]);

    if (auth === null) {
        return;
    }
    if (request === null && id != currentRequestId) {
        return <h2>Заявка с номером #{id} не найдена</h2>;
    } else if (request == undefined) {
        return <LoadingIndicator />;
    }

    const mapsDisplay =
        request == null || request.maps!.length == 0 ? (
            <div
                className="container"
                style={{
                    display: 'table',
                    textAlign: 'center'
                }}
            >
                <span
                    style={{
                        display: 'table-cell',
                        verticalAlign: 'middle'
                    }}
                >
                    <h3 className="text-body-secondary">
                        Пусто. <Link to="/maps">Выбрать карты.</Link>
                    </h3>
                </span>
            </div>
        ) : (
            <MapListComponent maps={request.maps!} showButtons={id == currentRequestId} />
        );
    return (
        <div className="container">
            <span>
                <h4>
                    Заявка <span className="badge text-bg-dark">#{id}</span>
                </h4>
                {mapsDisplay}
                <button className="btn btn-secondary" onClick={() => navigate(-1)}>
                    Назад
                </button>
            </span>
        </div>
    );
};
