import { FC, useEffect, useState } from 'react';
import { useCurrentRequestId, useAuth, useMapIds } from '../Core/Storage/DataSlice';
import { SearchMapsRequestVerbose } from '../Autogenerated/Backend';
import { SearchMapsRequestAPI } from '../Core/APIs/SearchMapsRequestAPI';
import { Link } from 'react-router-dom';

export const ShopcartComponent: FC = () => {
    const login = useAuth();
    const [request, setRequest] = useState<SearchMapsRequestVerbose | null>(null);
    const mapIds = useMapIds();
    const currentRequestId = useCurrentRequestId();

    useEffect(() => {
        async function getRequests() {
            if (currentRequestId !== null) {
                const request = await SearchMapsRequestAPI.GetRequest(currentRequestId);
                setRequest(request);
            }
        }
        getRequests();
    }, [currentRequestId, mapIds]);

    if (login === null) {
        return <></>;
    }

    const result =
        request === null ? (
            <div className="m-2">Карт не выбрано</div>
        ) : (
            <Link className="btn btn-link btn-outline-info" to="/cart">
                Карт выбрано: {request.maps?.length}
            </Link>
        );

    return <div className="p-1">{result}</div>;
};
