import { FC, useEffect, useState } from 'react';
import { useCurrentRequestId, useLogin } from '../Core/Storage/DataSlice';
import { SearchMapsRequest } from '../Autogenerated/Backend';
import { SearchMapsRequestAPI } from '../Core/APIs/SearchMapsRequestAPI';
import { Link } from 'react-router-dom';

export const ShopcartComponent: FC = () => {
    const login = useLogin();
    const [request, setRequest] = useState<SearchMapsRequest | null>(null);
    const currentRequestId = useCurrentRequestId();

    useEffect(() => {
        async function getRequests() {
            if (currentRequestId !== null) {
                const request = await SearchMapsRequestAPI.GetRequest(currentRequestId);
                setRequest(request);
            }
        }
        getRequests();
    }, [currentRequestId]);

    if (login === null) {
        return <></>;
    }

    if (request === null) {
        return <div>Карт не выбрано</div>;
    }

    return <Link to="/cart">Выбрано {request.mapsCount} карт</Link>;
};
