import axios from "axios";
import { BASE_API_URL } from "../../Configuration";
import { SearchMapsRequestVerbose } from "../../Autogenerated/Backend";

export abstract class SearchMapsRequestAPI {
    public static readonly SEARCH_MAPS_REQUEST_API_PATH = 'search_maps_request';

    public static GetRequest = async (requestId: number) => {
        const url = `${BASE_API_URL}/${this.SEARCH_MAPS_REQUEST_API_PATH}/${requestId}`;
        try {
            const result = await axios.get(url);
            const searchMapRequestVerbose: SearchMapsRequestVerbose = result.data;
            return searchMapRequestVerbose;
        } catch (error) {
            return null;
        }
    }

    public static AddMapToRequest = async (mapId: number) => {
        const url = `${BASE_API_URL}/${this.SEARCH_MAPS_REQUEST_API_PATH}/add_map/${mapId}`;
        try {
            const result = await axios.put(url);
            const searchMapsRequestId: number = result.data;
            return searchMapsRequestId;
        } catch (error) {
            return null;
        }
    }

    public static RemoveMapFromRequest = async (mapId: number) => {
        const url = `${BASE_API_URL}/${this.SEARCH_MAPS_REQUEST_API_PATH}/remove_map/${mapId}`;
        try {
            const result = await axios.delete(url);
            return result.status == 200;
        } catch (error) {
            return null;
        }
    }
}