import axios from "axios";
import { BASE_API_URL } from "../../Configuration";
import { User } from "../../Autogenerated/Backend";

export abstract class UserAPI {
    public static readonly USER_API_PATH = 'user';

    public static GetUser = async (userId: number) => {
        const url = `${BASE_API_URL}/${this.USER_API_PATH}/${userId}`;
        const result = await axios.get(url);
        if (result.status == 400) {
            return null;
        }
        const user: User = await result.data;
        return user;
    }
}