import { FC, useState, useEffect } from 'react';
import { SearchMapsRequest } from '../../Autogenerated/Backend';
import { LoadingIndicator } from '../UI/LoadingIndicator';
import { SearchMapsRequestAPI } from '../../Core/APIs/SearchMapsRequestAPI';
import { useAuth } from '../../Core/Storage/DataSlice';
import { useNavigate } from 'react-router-dom';
import { SearchMapsRequestRowComponent } from './SearchMapsRequestRow';

export const SearchMapsRequestListComponent: FC = () => {
    const [requests, setRequests] = useState<SearchMapsRequest[] | null>(null);
    const auth = useAuth();
    const navigate = useNavigate();

    useEffect(() => {
        async function loadData() {
            const requests = await SearchMapsRequestAPI.GetRequests();
            setRequests(requests);
        }

        loadData();
        if (auth === null) {
            navigate('/');
        }
    }, [auth, navigate]);

    if (requests === null) {
        return <LoadingIndicator />;
    }

    return (
        <div>
            <h3>Список заявок</h3>
            <table className="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Дата создания</th>
                        <th scope="col">Дата формирования</th>
                        <th scope="col">Дата завершения</th>
                        <th scope="col">Список карт</th>
                    </tr>
                </thead>
                <tbody>
                    {requests.map((r) => (
                        <SearchMapsRequestRowComponent searchMapsRequest={r} />
                    ))}
                </tbody>
            </table>
        </div>
    );
};
