import { FC } from 'react';
import { Map, MapStatus } from '../../../Autogenerated/Backend';
import { StaticDataAPI } from '../../../Core/APIs/StaticDataAPI';
import { Link } from 'react-router-dom';

function mapStatusToString(mapStatus?: MapStatus) {
    switch (mapStatus) {
        case MapStatus.Available:
            return 'Доступна';
        case MapStatus.Deleted:
            return 'Удалена';
        case MapStatus.Pending:
            return 'Ожидает подтверждения';

        default:
            return '[ДАННЫЕ ███████]';
    }
}

interface MapTableRowComponent {
    map: Map;
}

export const MapTableRowComponent: FC<MapTableRowComponent> = ({ map }) => {
    const coverImageUrl = StaticDataAPI.FormMapCoverUrl(map);
    const bgColor = '';
    const status = mapStatusToString(map.mapStatus);

    const description = map.description ? (
        <div className="accordion" id="descriptionAccordion">
            <div className="accordion-item">
                <h2 className="accordion-header">
                    <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target={`#collapse${map.id}`} aria-expanded="true">
                        Открыть
                    </button>
                </h2>
                <div id={`collapse${map.id}`} className="accordion-collapse collapse" data-bs-parent="#descriptionAccordion">
                    <div className="accordion-body">{map.description}</div>
                </div>
            </div>
        </div>
    ) : (
        <span className="text-body-secondary">Отсутствует</span>
    );
    return (
        <tr key={map.id}>
            <th className={bgColor} scope="row">
                <span className="badge text-bg-dark">{map.id}</span>
            </th>
            <td className={bgColor}>
                <div
                    style={{
                        height: '3rem',
                        position: 'relative'
                    }}
                >
                    <img
                        src={coverImageUrl}
                        alt="Minimap image"
                        style={{
                            maxWidth: '100%',
                            maxHeight: '100%',
                            resize: 'both',
                            position: 'absolute',
                            top: 0,
                            bottom: 0,
                            left: 0,
                            right: 0,
                            margin: 'auto',
                            width: 'auto',
                            height: 'auto',
                            border: '1px solid black'
                        }}
                    />
                </div>
            </td>
            <td className={bgColor}>{map.name}</td>
            <td className={bgColor}>{map.width}</td>
            <td className={bgColor}>{map.height}</td>
            <td className={bgColor}>{map.maxPlayersCount}</td>
            <td className={bgColor}>{description}</td>
            <td className={bgColor}>{status}</td>
            <td className={bgColor}>
                <Link className="btn btn-primary" to={`/maps/${map.id}`}>
                    Открыть
                </Link>
            </td>
        </tr>
    );
};
