import { FC, useEffect, useState, useRef } from 'react';
import { MapAPI } from '../../Core/APIs/MapAPI';
import { MapListComponent } from './MapList/MapList';
import { LoadingIndicator } from '../UI/LoadingIndicator';
import { Map, MapStatus } from '../../Autogenerated/Backend';
import { setFilterMapMaxPlayersCount, setFilterMapName, useAuth, useFilterMapMaxPlayersCount, useFilterMapName } from '../../Core/Storage/DataSlice';
import { useDispatch } from 'react-redux';

export const MapsPageComponent: FC = () => {
    const [maps, setMaps] = useState<Map[] | undefined>(undefined);
    const filterMapName = useFilterMapName();
    const filterMapMaxPlayersCount = useFilterMapMaxPlayersCount();
    const dispatch = useDispatch();
    const auth = useAuth();

    const filterNameInput = useRef<HTMLInputElement>(null);
    const maxPlayersCountInput = useRef<HTMLInputElement>(null);

    useEffect(() => {
        async function getMaps() {
            const maps = await MapAPI.GetMaps(filterMapName, filterMapMaxPlayersCount);
            setMaps(maps.filter((m) => m.mapStatus === MapStatus.Available));
            if (filterNameInput !== null && filterMapName) {
                filterNameInput.current!.value = filterMapName;
            }
        
            if (maxPlayersCountInput !== null && filterMapMaxPlayersCount) {
                maxPlayersCountInput.current!.value = filterMapMaxPlayersCount.toString();
            }
        }
        getMaps();

    }, [filterMapName, filterMapMaxPlayersCount, auth, filterNameInput, maxPlayersCountInput]);

    function handleSubmit(event: React.FormEvent) {
        dispatch(setFilterMapName(filterNameInput.current?.value));
        if (maxPlayersCountInput.current) {
            dispatch(setFilterMapMaxPlayersCount(parseInt(maxPlayersCountInput.current.value)));
        }
        event.preventDefault();
    }

    if (!maps) {
        return <LoadingIndicator />;
    }
    const mapsDisplay =
        maps.length == 0 ? (
            <div
                className="container"
                style={{
                    display: 'table',
                    textAlign: 'center'
                }}
            >
                <span
                    style={{
                        display: 'table-cell',
                        verticalAlign: 'middle'
                    }}
                >
                    <h3 className="text-body-secondary">Не найдено</h3>
                </span>
            </div>
        ) : (
            <MapListComponent maps={maps} showButtons={true} />
        );
    return (
        <div className="container" style={{ display: 'flex' }}>
            <div>
                <form method="get" className="card p-2 m-3" style={{ width: '250px' }} onSubmit={(e) => handleSubmit(e)}>
                    <div style={{ display: 'flex' }}>
                        <h5>Фильтры</h5>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="FilterMapName" className="form-label">
                            Название карты
                        </label>
                        <input type="text" className="form-control" id="FilterMapName" name="FilterMapName" ref={filterNameInput} />
                    </div>
                    <div className="mb-3">
                        <label htmlFor="FilterMapMaxPlayersCount" className="form-label">
                            Максимальное количество игроков
                        </label>
                        <input type="number" className="form-control" id="FilterMapMaxPlayersCount" name="FilterMapMaxPlayersCount" min="0" ref={maxPlayersCountInput} />
                    </div>
                    <button type="submit" className="btn btn-primary">
                        Применить
                    </button>
                </form>
            </div>
            {mapsDisplay}
        </div>
    );
};
