import { FC } from 'react';
import { Map } from '../../Autogenerated/Backend';
import { Link } from 'react-router-dom';

interface MapsSubListComponentProps {
    maps: Map[];
}

export const MapsSubListComponent: FC<MapsSubListComponentProps> = ({ maps }) => {
    return (
        <table className="table">
            <tbody>
                {maps.map((m) => (
                    <tr>
                        <th scope="row">
                            <Link to={`/maps/${m.id}`}>{m.name}</Link>
                        </th>
                    </tr>
                ))}
            </tbody>
        </table>
    );
};
