import { FC } from 'react';
import { Map } from '../../Autogenerated/Backend';

interface MapsSubListComponentProps {
    maps: Map[];
}

export const MapsSubListComponent: FC<MapsSubListComponentProps> = ({ maps }) => {
    return (
        <table className="table">
            {/* <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                </tr>
            </thead> */}
            <tbody>
                {maps.map((m) => (
                    <tr>
                        <th scope="row">{m.name}</th>
                    </tr>
                ))}
            </tbody>
        </table>
    );
};
